version: '3'

services:
  sum-service:
    build: .
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - sum-service
    environment:
      - A=10
      - B=20